# Generated by Django 2.2.5 on 2019-10-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190920_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteStocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('stock', models.CharField(max_length=10)),
            ],
        ),
    ]
