# Generated by Django 2.2.6 on 2019-10-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_notificationsrules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsrules',
            name='maxChange',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='notificationsrules',
            name='minChange',
            field=models.FloatField(null=True),
        ),
    ]
