# Generated by Django 2.2.6 on 2019-10-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20191016_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('notificationType', models.CharField(max_length=30)),
            ],
        ),
    ]
